version: '3.8'

services:
  pbl4:
    build: 
      dockerfile: Dockerfile
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
        APP_PORT: ${APP_PORT}
    container_name: pbl4
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
    restart: always
    volumes:
      - .:/home/app
